sudo: required

services:
  - docker

env:
  - VERSION=2.9.2
  - VERSION=2.9.3
  - VERSION=2.10.1
  - VERSION=2.10.2
  - VERSION=2.10.3
  - VERSION=2.10.4
  - VERSION=2.10.5
  - VERSION=2.10.6
  - VERSION=2.11.0
  - VERSION=2.11.1
  - VERSION=2.11.2
  - VERSION=2.11.4
  - VERSION=2.11.5
  - VERSION=2.11.6
  - VERSION=2.11.7
  - VERSION=2.11.8
  - VERSION=2.11.11
  - VERSION=2.12.0
  - VERSION=2.12.1
  - VERSION=2.12.2

script:
  - docker build -t abigail/scala:local "$VERSION" 
  - ./test abigail/scala:local
