#!/bin/sh

image="${1-abigail/scala:latest}"
echo "image: $image"

echo -n "testing running scala via stdin... "
docker run --rm "$image" bash -c 'echo util.Properties.versionString | scala' > /dev/null
if [ "$?" -eq 0 ] ; then echo "success"; else echo "failure"; exit 1; fi

echo -n "testing running scala via file... "
docker run --rm -v "$PWD/testresources:/testresources" "$image" scala "/testresources/testscript.scala" > /dev/null
if [ "$?" -eq 0 ] ; then echo "success"; else echo "failure"; exit 1; fi

echo -n "testing running scalac... "
docker run --rm -v "$PWD/testresources:/testresources" "$image" scalac "/testresources/TestClass.scala" > /dev/null
if [ "$?" -eq 0 ] ; then echo "success"; else echo "failure"; exit 1; fi

echo "all tests passed!"
